version: '3.8'

services:

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    networks:
        - proxybackend

  termadmissionmanagement.api:
    image: ${DOCKER_REGISTRY-}termadmissionmanagementapi
    build:
      context: .
      dockerfile: TermAdmissionManagement.API/Dockerfile
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge


