version: '3.8'

services:

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
      - "5050:8080"   # Truy cập Gateway tại http://localhost:5000
    depends_on:
      - termadmissionmanagement.api
      - authservice.api
    networks:
      - proxybackend

  termadmissionmanagement.api:
    image: ${DOCKER_REGISTRY-}termadmissionmanagementapi
    build:
      context: .
      dockerfile: TermAdmissionManagement.API/Dockerfile
    ports:
      - "5001:8080"   # Truy cập trực tiếp service này tại http://localhost:5001
    networks:
      - proxybackend

  authservice.api:
    image: ${DOCKER_REGISTRY-}authserviceapi
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile
    ports:
      - "5002:8080"   # Truy cập trực tiếp service này tại http://localhost:5022
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
